/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.validation;

import org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocation;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.Link}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkValidator {
	boolean validate();

	boolean validateAllocation(LinkAllocation value);
}
