/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.validation;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.NetworkTopology}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NetworkTopologyValidator {
	boolean validate();

}
