/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocation;

import org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.SubgraphNodeTemplate;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.SubgraphSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubgraphSpecificationValidator {
	boolean validate();

	boolean validateNodeTemplates(EList<SubgraphNodeTemplate> value);

	boolean validateConnectivity(int value);

	boolean validateLinkAllocation(LinkAllocation value);
}
