/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.blockchainsystemComponentRepository.validation;

import org.palladiosimulator.blockchainsystems.bscm.blockchainsystemComponentRepository.BlockValiationDurationSpecification;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.blockchainsystemComponentRepository.BlockValidatorComponent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlockValidatorComponentValidator {
	boolean validate();

	boolean validateValidationDuration(BlockValiationDurationSpecification value);
}
