/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.nodeallocation.validation;

import org.palladiosimulator.blockchainsystems.bscm.nodeenvironment.NodeResourceContainer;

import org.palladiosimulator.blockchainsystems.bscm.nodesystem.BlockchainSystemNodeAssemblyContext;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.nodeallocation.NodeAllocationContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeAllocationContextValidator {
	boolean validate();

	boolean validateAssemblyContext(BlockchainSystemNodeAssemblyContext value);

	boolean validateResourceContainer(NodeResourceContainer value);
}
