/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.attackmodel.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.blockchainsystems.bscm.attackmodel.Attack;
import org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackResult;
import org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackerNode;

import org.palladiosimulator.blockchainsystems.bscm.blockchainsystem.BlockchainSystem;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackScenario}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttackScenarioValidator {
	boolean validate();

	boolean validateAttack(Attack value);

	boolean validateAttackers(EList<AttackerNode> value);

	boolean validateBlockchainSystem(BlockchainSystem value);

	boolean validateResult(AttackResult value);
}
