/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.attackmodel.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackParameter;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.Attack}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttackValidator {
	boolean validate();

	boolean validateType(String value);

	boolean validateRequiredHashPower(double value);

	boolean validateDependsOnNetworkDelay(boolean value);

	boolean validateBaselineSuccessProbability(double value);

	boolean validateParameters(EList<AttackParameter> value);

	boolean validateGamma(double value);
}
