/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.attackmodel.validation;

import org.palladiosimulator.blockchainsystems.bscm.nodesystem.BlockchainSystemNodeSystem;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackerNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttackerNodeValidator {
	boolean validate();

	boolean validatePowerShare(double value);

	boolean validateLinkedNodeSystem(BlockchainSystemNodeSystem value);
}
