/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.attackmodel.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.blockchainsystems.bscm.attackmodel.ForkDepthEntry;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackResult}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttackResultValidator {
	boolean validate();

	boolean validateSuccess(boolean value);

	boolean validateDuration(double value);

	boolean validateAffectedBlocks(int value);

	boolean validateSuccessProbabilityObserved(double value);

	boolean validateAvgForkRate(double value);

	boolean validateStaleBlockRate(double value);

	boolean validateDoubleSpendCount(int value);

	boolean validateTimeToTakeover(double value);

	boolean validateForkDepthDistribution(EList<ForkDepthEntry> value);

	boolean validateAttackerRevenueRatio(double value);
}
