/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.attackmodel.validation;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.FinneyAttack}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FinneyAttackValidator {
	boolean validate();

	boolean validateNumberOfPreminedBlocks(int value);

	boolean validateWithholdTime(long value);

	boolean validateMerchantAcceptsZeroConf(boolean value);

	boolean validateDoubleSpendSuccessCount(int value);

	boolean validateObservedTimeToReleaseMs(long value);
}
