/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.attackmodel.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackerNode;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.MajorityAttack}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MajorityAttackValidator {
	boolean validate();

	boolean validateHashPowerShare(double value);

	boolean validateExpectedTakeoverTime(double value);

	boolean validateTargetConfirmationsToBreak(int value);

	boolean validateColludingPools(EList<AttackerNode> value);
}
