/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.attackmodel.validation;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.RaceAttack}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RaceAttackValidator {
	boolean validate();

	boolean validatePropagationAdvantage(long value);

	boolean validateTransactionADelay(long value);

	boolean validateTransactionBAcceleration(long value);

	boolean validateFeeDifferenceThreshold(double value);

	boolean validateZeroConfAcceptanceRisk(double value);

	boolean validateObservedDoubleSpends(int value);

	boolean validateAvgPropagationAdvMs(long value);
}
