/**
 */
package org.palladiosimulator.blockchainsystems.bscm.attackmodel.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.palladiosimulator.blockchainsystems.bscm.attackmodel.util.AttackmodelAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AttackmodelItemProviderAdapterFactory extends AttackmodelAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AttackmodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackScenario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttackScenarioItemProvider attackScenarioItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackScenario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttackScenarioAdapter() {
		if (attackScenarioItemProvider == null) {
			attackScenarioItemProvider = new AttackScenarioItemProvider(this);
		}

		return attackScenarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackerNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttackerNodeItemProvider attackerNodeItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackerNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttackerNodeAdapter() {
		if (attackerNodeItemProvider == null) {
			attackerNodeItemProvider = new AttackerNodeItemProvider(this);
		}

		return attackerNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackResult} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttackResultItemProvider attackResultItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackResult}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttackResultAdapter() {
		if (attackResultItemProvider == null) {
			attackResultItemProvider = new AttackResultItemProvider(this);
		}

		return attackResultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttackParameterItemProvider attackParameterItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.AttackParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttackParameterAdapter() {
		if (attackParameterItemProvider == null) {
			attackParameterItemProvider = new AttackParameterItemProvider(this);
		}

		return attackParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.ForkDepthEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForkDepthEntryItemProvider forkDepthEntryItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.ForkDepthEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForkDepthEntryAdapter() {
		if (forkDepthEntryItemProvider == null) {
			forkDepthEntryItemProvider = new ForkDepthEntryItemProvider(this);
		}

		return forkDepthEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.RaceAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RaceAttackItemProvider raceAttackItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.RaceAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRaceAttackAdapter() {
		if (raceAttackItemProvider == null) {
			raceAttackItemProvider = new RaceAttackItemProvider(this);
		}

		return raceAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.FinneyAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FinneyAttackItemProvider finneyAttackItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.FinneyAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFinneyAttackAdapter() {
		if (finneyAttackItemProvider == null) {
			finneyAttackItemProvider = new FinneyAttackItemProvider(this);
		}

		return finneyAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.SelfishMiningAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelfishMiningAttackItemProvider selfishMiningAttackItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.SelfishMiningAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelfishMiningAttackAdapter() {
		if (selfishMiningAttackItemProvider == null) {
			selfishMiningAttackItemProvider = new SelfishMiningAttackItemProvider(this);
		}

		return selfishMiningAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.EqualForkStubbornAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqualForkStubbornAttackItemProvider equalForkStubbornAttackItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.EqualForkStubbornAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqualForkStubbornAttackAdapter() {
		if (equalForkStubbornAttackItemProvider == null) {
			equalForkStubbornAttackItemProvider = new EqualForkStubbornAttackItemProvider(this);
		}

		return equalForkStubbornAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.LeadStubbornAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LeadStubbornAttackItemProvider leadStubbornAttackItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.LeadStubbornAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLeadStubbornAttackAdapter() {
		if (leadStubbornAttackItemProvider == null) {
			leadStubbornAttackItemProvider = new LeadStubbornAttackItemProvider(this);
		}

		return leadStubbornAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.TrailStubbornAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrailStubbornAttackItemProvider trailStubbornAttackItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.TrailStubbornAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrailStubbornAttackAdapter() {
		if (trailStubbornAttackItemProvider == null) {
			trailStubbornAttackItemProvider = new TrailStubbornAttackItemProvider(this);
		}

		return trailStubbornAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.MajorityAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MajorityAttackItemProvider majorityAttackItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.attackmodel.MajorityAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMajorityAttackAdapter() {
		if (majorityAttackItemProvider == null) {
			majorityAttackItemProvider = new MajorityAttackItemProvider(this);
		}

		return majorityAttackItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (attackScenarioItemProvider != null)
			attackScenarioItemProvider.dispose();
		if (attackerNodeItemProvider != null)
			attackerNodeItemProvider.dispose();
		if (attackResultItemProvider != null)
			attackResultItemProvider.dispose();
		if (attackParameterItemProvider != null)
			attackParameterItemProvider.dispose();
		if (forkDepthEntryItemProvider != null)
			forkDepthEntryItemProvider.dispose();
		if (raceAttackItemProvider != null)
			raceAttackItemProvider.dispose();
		if (finneyAttackItemProvider != null)
			finneyAttackItemProvider.dispose();
		if (selfishMiningAttackItemProvider != null)
			selfishMiningAttackItemProvider.dispose();
		if (equalForkStubbornAttackItemProvider != null)
			equalForkStubbornAttackItemProvider.dispose();
		if (leadStubbornAttackItemProvider != null)
			leadStubbornAttackItemProvider.dispose();
		if (trailStubbornAttackItemProvider != null)
			trailStubbornAttackItemProvider.dispose();
		if (majorityAttackItemProvider != null)
			majorityAttackItemProvider.dispose();
	}

}
