/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.nodesystem.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.blockchainsystems.bscm.nodesystem.BlockchainSystemNodeAssemblyContext;
import org.palladiosimulator.blockchainsystems.bscm.nodesystem.NodeBehaviorSpecification;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.nodesystem.BlockchainSystemNodeSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlockchainSystemNodeSystemValidator {
	boolean validate();

	boolean validateMiningProcessAssembly(BlockchainSystemNodeAssemblyContext value);

	boolean validateBlockValidatorAssembly(BlockchainSystemNodeAssemblyContext value);

	boolean validateAssemblyContexts(EList<BlockchainSystemNodeAssemblyContext> value);

	boolean validateBehavior(NodeBehaviorSpecification value);
}
