/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.geographicalregions.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.blockchainsystems.bscm.geographicalregions.GeographicalRegion;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.geographicalregions.GeographicalRegionsSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GeographicalRegionsSpecificationValidator {
	boolean validate();

	boolean validateRegions(EList<GeographicalRegion> value);
}
