/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.linkallocation.validation;

import org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkLatencySpecification;
import org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkThroughputSpecification;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkAllocationValidator {
	boolean validate();

	boolean validateLatencySpecification(LinkLatencySpecification value);

	boolean validateThroughputSpecification(LinkThroughputSpecification value);
}
