/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.linkallocation.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocation;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocationRepository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkAllocationRepositoryValidator {
	boolean validate();

	boolean validateLinkAllocations(EList<LinkAllocation> value);
}
