/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.blockchainsystem.validation;

import org.palladiosimulator.blockchainsystems.bscm.blockchainsystem.BlockchainSystemSpecification;

import org.palladiosimulator.blockchainsystems.bscm.geographicalregions.GeographicalRegionsSpecification;

import org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.P2PNetwork;

import org.palladiosimulator.blockchainsystems.bscm.transactions.TransactionsSpecification;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.blockchainsystem.BlockchainSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlockchainSystemValidator {
	boolean validate();

	boolean validateNetwork(P2PNetwork value);

	boolean validateSpecification(BlockchainSystemSpecification value);

	boolean validateTransactionsSpecification(TransactionsSpecification value);

	boolean validateGeographicalRegionsSpecification(GeographicalRegionsSpecification value);
}
