/**
 *
 * $Id$
 */
package org.palladiosimulator.blockchainsystems.bscm.blockchainsystem.validation;

/**
 * A sample validator interface for {@link org.palladiosimulator.blockchainsystems.bscm.blockchainsystem.BlockchainSystemSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlockchainSystemSpecificationValidator {
	boolean validate();

	boolean validateMeanBlockTime(double value);

	boolean validateNumOfRequiredSecurityConfirmations(int value);

	boolean validateMaxBlockSize(int value);

	boolean validateBlockReward(double value);
}
